version: '3.7'

services:
  frontend:
    depends_on:
      - backend
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  backend:
    depends_on:
      - redis
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python3 main.py
  
  redis:
    image: redis:6-alpine
    container_name: redis
    restart: unless-stopped
